version: "3.9"
services:
  tohuynhgithubio-dev:
    image: tohuynhgithubio-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    init: true
    volumes:
      - type: bind
        source: .
        target: /usr/src/app/
      - type: volume
        source: node_modules
        target: /usr/src/app/node_modules
    networks:
      - frontend
    ports:
      - 3000:3000
networks:
  frontend:
volumes:
  node_modules: