version: "3.9"
services:
# what happens if this fails? sut doesn't start, need to exit 1
  tohuynhgithubio:
    image: "${TESTING_IMAGE}"
    init: true
    ports:
      - 80:8080
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  
  sut:
    image: curlimages/curl
    init: true
    depends_on:
      tohuynhgithubio:
        condition: service_healthy
    command: curl --fail http://tohuynhgithubio:8080 || exit 1