version: "3.9"
services:
  tohuynhgithubio-nginx:
    image: tohuynhgithubio-nginx
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    ports:
      - 80:8080
      - 443:443
    volumes:
      - type: bind
        source: ./certs
        target: /etc/nginx/certs
    restart: unless-stopped
