version: "3.9"
services:
  tohuynhgithubio:
    image: "${TESTING_IMAGE}"
    init: true
    ports:
      - 80:8080
  
  sut:
    image: curlimages/curl
    init: true
    depends_on:
      tohuynhgithubio:
        condition: service_started
    command: curl --fail http://tohuynhgithubio:8080 || exit 1