version: "3.9"
services:
  tohuynhgithubio-nginx:
    image: tohuynhgithubio-nginx
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    ports:
      - 80:8080
    restart: unless-stopped